---

version: 1

disable_existing_loggers: False

formatters:

    simple:

        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

            
handlers:

    stream_handler:

        class: logging.StreamHandler

        level: INFO

        formatter: simple

        stream: ext://sys.stdout


    file_handler:

        class: logging.handlers.TimedRotatingFileHandler

        level: DEBUG

        formatter: simple

        when: 'D'

        interval: 7

        encoding: utf8


root:

    level: INFO

    handlers: [stream_handler, file_handler]
